setup:
	@make --no-print-directory -f cadcfg.mk all install
	@make --no-print-directory -f cadman.mk all install

clean:
	@make --no-print-directory -f cadcfg.mk clean_cadcfg
	@make --no-print-directory -f cadman.mk clean_cadman
