# Merge two GDSII files together by running Calibre DESIGNrev in batch mode.
# For example metal fill generated by Calibre nmDRC, and a full chip.
#
# Usage: source fill_merge.tcl fullchip.gds fill.gds
#**************************************************
#
# Copyright (c) Mentor Graphics Corporation 2006 All Rights Reserved.
# THIS WORK CONTAINS TRADE SECRET AND PROPRIETARY INFORMATION
# WHICH IS THE PROPERTY OF MENTOR GRAPHICS CORPORATION OR ITS
# LICENSORS AND IS SUBJECT TO LICENSE TERMS.
#
# DISCLAIMER OF WARRANTY:  Unless otherwise agreed in writing,
# Mentor Graphics software and associated files are provided "as is"
# and without warranty.  Mentor Graphics has no obligation to support
# or otherwise maintain software.  Mentor Graphics makes no warranties,
# express or implied with respect to software including any warranty
# of merchantability or fitness for a particular purpose.
#
# LIMITATION OF LIABILITY: Mentor Graphics is not liable for any property
# damage, personal injury, loss of profits, interruption of business, or for
# any other special, consequential or incidental damages, however caused,
# whether for breach of warranty, contract, tort (including negligence),
# strict liability or otherwise. In no event shall Mentor Graphics'
# liability exceed the amount paid for the product giving rise to the claim.

set gds0 [lindex $argv 0]
set gds1 [lindex $argv 1]
set L0 [layout create $gds0]
set L1 [layout create $gds1]
set L2 [layout merge $L0 $L1 0 -mode append]
$L2 update
set slen [string length $gds0]
set cellname [string range $gds0 0 end-4]
set cellext "_with_fill.gds"
set newgds $cellname$cellext
puts "$newgds"
$L2 gdsout $newgds
